using Microsoft.Extensions.Options;

namespace PursuitHQ.API.Services
{
    /// <summary>
    /// Saves uploads to a folder on disk. Development implementation - swap for
    /// an Azure Blob or S3 version in production without changing anything else.
    /// </summary>
    public class LocalFileStorageService : IFileStorageService
    {
        private readonly string _root;
        private readonly ILogger<LocalFileStorageService> _logger;

        public LocalFileStorageService(
            IOptions<FileStorageOptions> options,
            IWebHostEnvironment env,
            ILogger<LocalFileStorageService> logger)
        {
            _logger = logger;

            // ContentRootPath, not WebRootPath: files must NOT sit in wwwroot,
            // where the server would hand them to anyone who guessed the URL.
            // Every download goes through an authorized endpoint instead.
            _root = Path.Combine(env.ContentRootPath, options.Value.LocalPath);

            Directory.CreateDirectory(_root);
        }

        public async Task<string> SaveAsync(Stream content, string originalFileName, CancellationToken ct = default)
        {
            // The client's file name is never used on disk. It could contain
            // path characters ("../../appsettings.json") or collide with another
            // student's upload. A GUID avoids both problems.
            var extension = Path.GetExtension(originalFileName).ToLowerInvariant();
            var storedName = $"{Guid.NewGuid():N}{extension}";

            // Spread files across subfolders so no single directory ends up with
            // tens of thousands of entries.
            var subFolder = storedName[..2];
            var folderPath = Path.Combine(_root, subFolder);
            Directory.CreateDirectory(folderPath);

            var fullPath = Path.Combine(folderPath, storedName);

            await using (var file = File.Create(fullPath))
            {
                await content.CopyToAsync(file, ct);
            }

            // Store a relative key, so moving the storage folder does not
            // invalidate every row in the database.
            return Path.Combine(subFolder, storedName).Replace("\\", "/");
        }

        public Task<Stream> OpenAsync(string storedPath, CancellationToken ct = default)
        {
            var fullPath = ResolveSafePath(storedPath);

            if (!File.Exists(fullPath))
            {
                throw new FileNotFoundException("Stored file is missing.", storedPath);
            }

            Stream stream = File.OpenRead(fullPath);
            return Task.FromResult(stream);
        }

        public Task DeleteAsync(string storedPath, CancellationToken ct = default)
        {
            try
            {
                var fullPath = ResolveSafePath(storedPath);
                if (File.Exists(fullPath)) File.Delete(fullPath);
            }
            catch (Exception ex)
            {
                // A file we cannot delete should not fail the whole request. The
                // database row is what matters; log the orphan and move on.
                _logger.LogWarning(ex, "Could not delete stored file {StoredPath}", storedPath);
            }

            return Task.CompletedTask;
        }

        /// <summary>
        /// Resolves a stored key to a full path and refuses anything that
        /// escapes the storage root. Defence in depth: keys are generated by us,
        /// but this guarantees a malformed one cannot reach other files.
        /// </summary>
        private string ResolveSafePath(string storedPath)
        {
            var fullPath = Path.GetFullPath(Path.Combine(_root, storedPath));
            var rootPath = Path.GetFullPath(_root);

            if (!fullPath.StartsWith(rootPath, StringComparison.OrdinalIgnoreCase))
            {
                throw new UnauthorizedAccessException("Resolved path is outside the storage root.");
            }

            return fullPath;
        }
    }
}
